# Generated by Django 3.2 on 2022-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_deliver_to',
            field=models.CharField(default='Ukraine', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_coordinates',
            field=models.CharField(default='112.333', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Some Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+3803226442', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_address',
            field=models.CharField(default='Some Address', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region_deliver_to',
            field=models.CharField(default='Lviv oblast', max_length=100),
            preserve_default=False,
        ),
    ]
